rm -Rf    jmusic/src/main/java/jm/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/CVS/Root
rm -Rf    jmusic/src/main/java/jm/CVS/allclasses-frame.html
rm -Rf    jmusic/src/main/java/jm/CVS/allclasses-noframe.html
rm -Rf    jmusic/src/main/java/jm/CVS/constant-values.html
rm -Rf    jmusic/src/main/java/jm/CVS/deprecated-list.html
rm -Rf    jmusic/src/main/java/jm/CVS/help-doc.html
rm -Rf    jmusic/src/main/java/jm/CVS/index-all.html
rm -Rf    jmusic/src/main/java/jm/CVS/index.html
rm -Rf    jmusic/src/main/java/jm/CVS/jm/JMC.html
rm -Rf    jmusic/src/main/java/jm/CVS/jm/package-frame.html
rm -Rf    jmusic/src/main/java/jm/CVS/jm/package-summary.html
rm -Rf    jmusic/src/main/java/jm/CVS/jm/package-tree.html
rm -Rf    jmusic/src/main/java/jm/CVS/overview-tree.html
rm -Rf    jmusic/src/main/java/jm/CVS/package-list
rm -Rf    jmusic/src/main/java/jm/CVS/resources/inherit.gif
rm -Rf    jmusic/src/main/java/jm/CVS/stylesheet.css
rm -Rf    jmusic/src/main/java/jm/audio/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/audio/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/audio/CVS/Root
rm -Rf    jmusic/src/main/java/jm/audio/io/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/audio/io/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/audio/io/CVS/Root
rm -Rf    jmusic/src/main/java/jm/audio/math/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/audio/math/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/audio/math/CVS/Root
rm -Rf    jmusic/src/main/java/jm/audio/synth/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/audio/synth/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/audio/synth/CVS/Root
rm -Rf    jmusic/src/main/java/jm/constants/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/constants/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/constants/CVS/Root
rm -Rf    jmusic/src/main/java/jm/gui/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/gui/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/gui/CVS/Root
rm -Rf    jmusic/src/main/java/jm/gui/cpn/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/gui/cpn/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/gui/cpn/CVS/Root
rm -Rf    jmusic/src/main/java/jm/gui/cpn/graphics/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/gui/cpn/graphics/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/gui/cpn/graphics/CVS/Root
rm -Rf    jmusic/src/main/java/jm/gui/graph/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/gui/graph/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/gui/graph/CVS/Root
rm -Rf    jmusic/src/main/java/jm/gui/helper/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/gui/helper/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/gui/helper/CVS/Root
rm -Rf    jmusic/src/main/java/jm/gui/histogram/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/gui/histogram/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/gui/histogram/CVS/Root
rm -Rf    jmusic/src/main/java/jm/gui/show/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/gui/show/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/gui/show/CVS/Root
rm -Rf    jmusic/src/main/java/jm/gui/sketch/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/gui/sketch/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/gui/sketch/CVS/Root
rm -Rf    jmusic/src/main/java/jm/gui/wave/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/gui/wave/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/gui/wave/CVS/Root
rm -Rf    jmusic/src/main/java/jm/midi/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/midi/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/midi/CVS/Root
rm -Rf    jmusic/src/main/java/jm/midi/event/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/midi/event/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/midi/event/CVS/Root
rm -Rf    jmusic/src/main/java/jm/music/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/music/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/music/CVS/Root
rm -Rf    jmusic/src/main/java/jm/music/data/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/music/data/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/music/data/CVS/Root
rm -Rf    jmusic/src/main/java/jm/music/net/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/music/net/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/music/net/CVS/Root
rm -Rf    jmusic/src/main/java/jm/music/rt/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/music/rt/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/music/rt/CVS/Root
rm -Rf    jmusic/src/main/java/jm/music/tools/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/music/tools/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/music/tools/CVS/Root
rm -Rf    jmusic/src/main/java/jm/music/tools/ca/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/music/tools/ca/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/music/tools/ca/CVS/Root
rm -Rf    jmusic/src/main/java/jm/music/tools/fuzzy/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/music/tools/fuzzy/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/music/tools/fuzzy/CVS/Root
rm -Rf    jmusic/src/main/java/jm/music/tools/ga/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/music/tools/ga/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/music/tools/ga/CVS/Root
rm -Rf    jmusic/src/main/java/jm/util/CVS/Entries
rm -Rf    jmusic/src/main/java/jm/util/CVS/Repository
rm -Rf    jmusic/src/main/java/jm/util/CVS/Root
